# Generated by Django 4.2.7 on 2024-03-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_label', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('emotion_prompt', models.TextField()),
                ('chat', models.TextField()),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaries.diary')),
            ],
            options={
                'db_table': 'emotion',
            },
        ),
    ]
