# Generated by Django 4.2.7 on 2024-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=100)),
                ('music_url', models.URLField()),
            ],
            options={
                'db_table': 'music',
                'managed': True,
            },
        ),
    ]
